// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: gateway.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InputRequest 输入安全审计请求。
type InputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`                                                                               // 待审计的原始提示词内容。
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 可选的元数据，用于透传流量来源、用户 ID 等上下文。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputRequest) Reset() {
	*x = InputRequest{}
	mi := &file_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputRequest) ProtoMessage() {}

func (x *InputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputRequest.ProtoReflect.Descriptor instead.
func (*InputRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *InputRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *InputRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// InputResponse 输入安全审计响应。
type InputResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Safe            bool                   `protobuf:"varint,1,opt,name=safe,proto3" json:"safe,omitempty"`                                             // 审计是否通过。
	SanitizedPrompt string                 `protobuf:"bytes,2,opt,name=sanitized_prompt,json=sanitizedPrompt,proto3" json:"sanitized_prompt,omitempty"` // 脱敏或修复后的提示词（若未通过审计，此字段可能为空）。
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                                          // 拦截原因（如果 safe 为 false）。
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InputResponse) Reset() {
	*x = InputResponse{}
	mi := &file_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputResponse) ProtoMessage() {}

func (x *InputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputResponse.ProtoReflect.Descriptor instead.
func (*InputResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *InputResponse) GetSafe() bool {
	if x != nil {
		return x.Safe
	}
	return false
}

func (x *InputResponse) GetSanitizedPrompt() string {
	if x != nil {
		return x.SanitizedPrompt
	}
	return ""
}

func (x *InputResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// OutputRequest 输出内容审计请求。
type OutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseText  string                 `protobuf:"bytes,1,opt,name=response_text,json=responseText,proto3" json:"response_text,omitempty"` // AI 生成的原始回答文本。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputRequest) Reset() {
	*x = OutputRequest{}
	mi := &file_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputRequest) ProtoMessage() {}

func (x *OutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputRequest.ProtoReflect.Descriptor instead.
func (*OutputRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *OutputRequest) GetResponseText() string {
	if x != nil {
		return x.ResponseText
	}
	return ""
}

// OutputResponse 输出内容审计响应。
type OutputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Safe          bool                   `protobuf:"varint,1,opt,name=safe,proto3" json:"safe,omitempty"`                                       // 响应内容是否合规、可靠。
	SanitizedText string                 `protobuf:"bytes,2,opt,name=sanitized_text,json=sanitizedText,proto3" json:"sanitized_text,omitempty"` // 经过修剪或掩码处理后的最终文本。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputResponse) Reset() {
	*x = OutputResponse{}
	mi := &file_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputResponse) ProtoMessage() {}

func (x *OutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputResponse.ProtoReflect.Descriptor instead.
func (*OutputResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *OutputResponse) GetSafe() bool {
	if x != nil {
		return x.Safe
	}
	return false
}

func (x *OutputResponse) GetSanitizedText() string {
	if x != nil {
		return x.SanitizedText
	}
	return ""
}

// CacheRequest 语义缓存查询请求。
type CacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"` // 当前请求的提示词，用于计算向量相似度。
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`   // 模型名称，用于物理隔离。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheRequest) Reset() {
	*x = CacheRequest{}
	mi := &file_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheRequest) ProtoMessage() {}

func (x *CacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheRequest.ProtoReflect.Descriptor instead.
func (*CacheRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *CacheRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CacheRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

// CacheResponse 语义缓存查询结果。
type CacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hit           bool                   `protobuf:"varint,1,opt,name=hit,proto3" json:"hit,omitempty"`          // 是否命中缓存。
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"` // 缓存的回答内容（仅当 hit 为 true 时有效）。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheResponse) Reset() {
	*x = CacheResponse{}
	mi := &file_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheResponse) ProtoMessage() {}

func (x *CacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheResponse.ProtoReflect.Descriptor instead.
func (*CacheResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *CacheResponse) GetHit() bool {
	if x != nil {
		return x.Hit
	}
	return false
}

func (x *CacheResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

// TokenRequest Token 统计请求。
type TokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`   // 需要统计的文本内容。
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"` // 统计所参照的模型家族（例如 "gpt-4", "gpt-3.5-turbo"）。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *TokenRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TokenRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

// TokenResponse Token 统计结果。
type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // 计算出的 Token 数量。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *TokenResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_gateway_proto protoreflect.FileDescriptor

const file_gateway_proto_rawDesc = "" +
	"\n" +
	"\rgateway.proto\x12\agateway\"\xa4\x01\n" +
	"\fInputRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12?\n" +
	"\bmetadata\x18\x02 \x03(\v2#.gateway.InputRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\rInputResponse\x12\x12\n" +
	"\x04safe\x18\x01 \x01(\bR\x04safe\x12)\n" +
	"\x10sanitized_prompt\x18\x02 \x01(\tR\x0fsanitizedPrompt\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"4\n" +
	"\rOutputRequest\x12#\n" +
	"\rresponse_text\x18\x01 \x01(\tR\fresponseText\"K\n" +
	"\x0eOutputResponse\x12\x12\n" +
	"\x04safe\x18\x01 \x01(\bR\x04safe\x12%\n" +
	"\x0esanitized_text\x18\x02 \x01(\tR\rsanitizedText\"<\n" +
	"\fCacheRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"=\n" +
	"\rCacheResponse\x12\x10\n" +
	"\x03hit\x18\x01 \x01(\bR\x03hit\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\"8\n" +
	"\fTokenRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"%\n" +
	"\rTokenResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count2\xff\x01\n" +
	"\aAiLogic\x12;\n" +
	"\n" +
	"CheckInput\x12\x15.gateway.InputRequest\x1a\x16.gateway.InputResponse\x12>\n" +
	"\vCheckOutput\x12\x16.gateway.OutputRequest\x1a\x17.gateway.OutputResponse\x129\n" +
	"\bGetCache\x12\x15.gateway.CacheRequest\x1a\x16.gateway.CacheResponse\x12<\n" +
	"\vCountTokens\x12\x15.gateway.TokenRequest\x1a\x16.gateway.TokenResponseB\"Z github.com/ai-gateway/core/protob\x06proto3"

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData []byte
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)))
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_gateway_proto_goTypes = []any{
	(*InputRequest)(nil),   // 0: gateway.InputRequest
	(*InputResponse)(nil),  // 1: gateway.InputResponse
	(*OutputRequest)(nil),  // 2: gateway.OutputRequest
	(*OutputResponse)(nil), // 3: gateway.OutputResponse
	(*CacheRequest)(nil),   // 4: gateway.CacheRequest
	(*CacheResponse)(nil),  // 5: gateway.CacheResponse
	(*TokenRequest)(nil),   // 6: gateway.TokenRequest
	(*TokenResponse)(nil),  // 7: gateway.TokenResponse
	nil,                    // 8: gateway.InputRequest.MetadataEntry
}
var file_gateway_proto_depIdxs = []int32{
	8, // 0: gateway.InputRequest.metadata:type_name -> gateway.InputRequest.MetadataEntry
	0, // 1: gateway.AiLogic.CheckInput:input_type -> gateway.InputRequest
	2, // 2: gateway.AiLogic.CheckOutput:input_type -> gateway.OutputRequest
	4, // 3: gateway.AiLogic.GetCache:input_type -> gateway.CacheRequest
	6, // 4: gateway.AiLogic.CountTokens:input_type -> gateway.TokenRequest
	1, // 5: gateway.AiLogic.CheckInput:output_type -> gateway.InputResponse
	3, // 6: gateway.AiLogic.CheckOutput:output_type -> gateway.OutputResponse
	5, // 7: gateway.AiLogic.GetCache:output_type -> gateway.CacheResponse
	7, // 8: gateway.AiLogic.CountTokens:output_type -> gateway.TokenResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}
