// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: gateway.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiLogic_CheckInput_FullMethodName  = "/gateway.AiLogic/CheckInput"
	AiLogic_CheckOutput_FullMethodName = "/gateway.AiLogic/CheckOutput"
	AiLogic_GetCache_FullMethodName    = "/gateway.AiLogic/GetCache"
	AiLogic_CountTokens_FullMethodName = "/gateway.AiLogic/CountTokens"
)

// AiLogicClient is the client API for AiLogic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AiLogicClient interface {
	// Input Guardrail: Detect PII and check for prompt injection
	CheckInput(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*InputResponse, error)
	// Output Guardrail: Detect hallucinations or sensitive data leakage
	CheckOutput(ctx context.Context, in *OutputRequest, opts ...grpc.CallOption) (*OutputResponse, error)
	// Semantic Cache Check
	GetCache(ctx context.Context, in *CacheRequest, opts ...grpc.CallOption) (*CacheResponse, error)
	// Token Counting (Nitro)
	CountTokens(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
}

type aiLogicClient struct {
	cc grpc.ClientConnInterface
}

func NewAiLogicClient(cc grpc.ClientConnInterface) AiLogicClient {
	return &aiLogicClient{cc}
}

func (c *aiLogicClient) CheckInput(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*InputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InputResponse)
	err := c.cc.Invoke(ctx, AiLogic_CheckInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiLogicClient) CheckOutput(ctx context.Context, in *OutputRequest, opts ...grpc.CallOption) (*OutputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OutputResponse)
	err := c.cc.Invoke(ctx, AiLogic_CheckOutput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiLogicClient) GetCache(ctx context.Context, in *CacheRequest, opts ...grpc.CallOption) (*CacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CacheResponse)
	err := c.cc.Invoke(ctx, AiLogic_GetCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiLogicClient) CountTokens(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, AiLogic_CountTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiLogicServer is the server API for AiLogic service.
// All implementations must embed UnimplementedAiLogicServer
// for forward compatibility.
type AiLogicServer interface {
	// Input Guardrail: Detect PII and check for prompt injection
	CheckInput(context.Context, *InputRequest) (*InputResponse, error)
	// Output Guardrail: Detect hallucinations or sensitive data leakage
	CheckOutput(context.Context, *OutputRequest) (*OutputResponse, error)
	// Semantic Cache Check
	GetCache(context.Context, *CacheRequest) (*CacheResponse, error)
	// Token Counting (Nitro)
	CountTokens(context.Context, *TokenRequest) (*TokenResponse, error)
	mustEmbedUnimplementedAiLogicServer()
}

// UnimplementedAiLogicServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiLogicServer struct{}

func (UnimplementedAiLogicServer) CheckInput(context.Context, *InputRequest) (*InputResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckInput not implemented")
}
func (UnimplementedAiLogicServer) CheckOutput(context.Context, *OutputRequest) (*OutputResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckOutput not implemented")
}
func (UnimplementedAiLogicServer) GetCache(context.Context, *CacheRequest) (*CacheResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCache not implemented")
}
func (UnimplementedAiLogicServer) CountTokens(context.Context, *TokenRequest) (*TokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountTokens not implemented")
}
func (UnimplementedAiLogicServer) mustEmbedUnimplementedAiLogicServer() {}
func (UnimplementedAiLogicServer) testEmbeddedByValue()                 {}

// UnsafeAiLogicServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiLogicServer will
// result in compilation errors.
type UnsafeAiLogicServer interface {
	mustEmbedUnimplementedAiLogicServer()
}

func RegisterAiLogicServer(s grpc.ServiceRegistrar, srv AiLogicServer) {
	// If the following call panics, it indicates UnimplementedAiLogicServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiLogic_ServiceDesc, srv)
}

func _AiLogic_CheckInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiLogicServer).CheckInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiLogic_CheckInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiLogicServer).CheckInput(ctx, req.(*InputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiLogic_CheckOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiLogicServer).CheckOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiLogic_CheckOutput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiLogicServer).CheckOutput(ctx, req.(*OutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiLogic_GetCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiLogicServer).GetCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiLogic_GetCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiLogicServer).GetCache(ctx, req.(*CacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiLogic_CountTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiLogicServer).CountTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiLogic_CountTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiLogicServer).CountTokens(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AiLogic_ServiceDesc is the grpc.ServiceDesc for AiLogic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiLogic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.AiLogic",
	HandlerType: (*AiLogicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckInput",
			Handler:    _AiLogic_CheckInput_Handler,
		},
		{
			MethodName: "CheckOutput",
			Handler:    _AiLogic_CheckOutput_Handler,
		},
		{
			MethodName: "GetCache",
			Handler:    _AiLogic_GetCache_Handler,
		},
		{
			MethodName: "CountTokens",
			Handler:    _AiLogic_CountTokens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}
