# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gateway_pb2 as gateway__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiLogicStub(object):
    """AiLogic 定义了 AI 网关与周边智能/加速层之间的核心通信接口。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckInput = channel.unary_unary(
                '/gateway.AiLogic/CheckInput',
                request_serializer=gateway__pb2.InputRequest.SerializeToString,
                response_deserializer=gateway__pb2.InputResponse.FromString,
                _registered_method=True)
        self.CheckOutput = channel.unary_unary(
                '/gateway.AiLogic/CheckOutput',
                request_serializer=gateway__pb2.OutputRequest.SerializeToString,
                response_deserializer=gateway__pb2.OutputResponse.FromString,
                _registered_method=True)
        self.GetCache = channel.unary_unary(
                '/gateway.AiLogic/GetCache',
                request_serializer=gateway__pb2.CacheRequest.SerializeToString,
                response_deserializer=gateway__pb2.CacheResponse.FromString,
                _registered_method=True)
        self.CountTokens = channel.unary_unary(
                '/gateway.AiLogic/CountTokens',
                request_serializer=gateway__pb2.TokenRequest.SerializeToString,
                response_deserializer=gateway__pb2.TokenResponse.FromString,
                _registered_method=True)


class AiLogicServicer(object):
    """AiLogic 定义了 AI 网关与周边智能/加速层之间的核心通信接口。
    """

    def CheckInput(self, request, context):
        """CheckInput 执行输入侧的安全审计与脱敏。
        负责 PII（敏感个人信息）识别、提示词注入（Prompt Injection）检测等功能。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckOutput(self, request, context):
        """CheckOutput 执行输出侧的安全审计与内容合规检查。
        用于识别潜在的 AI 幻觉、敏感信息泄露或违反内容策略的响应。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCache(self, request, context):
        """GetCache 语义级缓存检查。
        基于向量相似度匹配，返回最接近的历史回答以降低消耗并提升响应速度。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountTokens(self, request, context):
        """CountTokens 统计请求或响应的 Token 消耗（由 Rust 侧 Nitro 引擎提供支持）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiLogicServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckInput': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckInput,
                    request_deserializer=gateway__pb2.InputRequest.FromString,
                    response_serializer=gateway__pb2.InputResponse.SerializeToString,
            ),
            'CheckOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckOutput,
                    request_deserializer=gateway__pb2.OutputRequest.FromString,
                    response_serializer=gateway__pb2.OutputResponse.SerializeToString,
            ),
            'GetCache': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCache,
                    request_deserializer=gateway__pb2.CacheRequest.FromString,
                    response_serializer=gateway__pb2.CacheResponse.SerializeToString,
            ),
            'CountTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.CountTokens,
                    request_deserializer=gateway__pb2.TokenRequest.FromString,
                    response_serializer=gateway__pb2.TokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gateway.AiLogic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gateway.AiLogic', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiLogic(object):
    """AiLogic 定义了 AI 网关与周边智能/加速层之间的核心通信接口。
    """

    @staticmethod
    def CheckInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.AiLogic/CheckInput',
            gateway__pb2.InputRequest.SerializeToString,
            gateway__pb2.InputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.AiLogic/CheckOutput',
            gateway__pb2.OutputRequest.SerializeToString,
            gateway__pb2.OutputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.AiLogic/GetCache',
            gateway__pb2.CacheRequest.SerializeToString,
            gateway__pb2.CacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.AiLogic/CountTokens',
            gateway__pb2.TokenRequest.SerializeToString,
            gateway__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
